const productsData = [

 

  {"OffersNo":"OF23-00482","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102301","DescriptionOffre":"Lot Far Away the Moon","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":79.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":147.000,"DescrOffers":"1 Parfum + 1 Lait Corps"},
  {"OffersNo":"OF23-00527","CatalogueNo":"CAT22-61","TypeOffre":"007","NoArticleFacturation":"BA102301","DescriptionOffre":"Offre Wow 1","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":26.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":80.000,"DescrOffers":"1 Brume + 1 Gel-Douche + 1 Shampo + 1 Crème"}
  ,
  {"OffersNo":"OF23-00483","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102302","DescriptionOffre":"Lot Célèbre","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":69.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":125.000,"DescrOffers":"1 Eau de Toilette + 1 Brume"}
  ,{"OffersNo":"OF23-00528","CatalogueNo":"CAT22-61","TypeOffre":"007","NoArticleFacturation":"BA102302","DescriptionOffre":"Offre Wow 2","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":26.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":78.000,"DescrOffers":"1 Brume + 1 Gel-Douche + 1 Crème + 1 Déo"},
  {"OffersNo":"OF23-00484","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102303","DescriptionOffre":"Lot Musk Marine","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":49.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":98.000,"DescrOffers":"1 Eau de Toilette + 1 Déo à Bille"},
  {"OffersNo":"OF23-00485","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000724","DescriptionOffre":"Lot Imari","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":77.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":208.000,"DescrOffers":"2 Imari au choix"},
  {"OffersNo":"OF23-00530","CatalogueNo":"CAT22-61","TypeOffre":"007","NoArticleFacturation":"BA102303","DescriptionOffre":"Lot Soin","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":39.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":108.000,"DescrOffers":"1 Crème dépilatoire + 1 Crème Multi-usage"},{
  "OffersNo":"OF23-00486","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000725","DescriptionOffre":"Lot Black Suede","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":109.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":232.000,"DescrOffers":"2 Black Suede au choix"},
  {"OffersNo":"OF23-00531","CatalogueNo":"CAT22-61","TypeOffre":"007","NoArticleFacturation":"BA102304","DescriptionOffre":"Lot Dance","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":39.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":114.000,"DescrOffers":"1 Eau de Toilette + 1 Déo à Bille + 1 Crème pour les Mains "},
  {"OffersNo":"OF23-00487","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000726","DescriptionOffre":"Lot Brume","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":39.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":70.000,"DescrOffers":"2 Brumes au choix"},
  {"OffersNo":"OF23-00532","CatalogueNo":"CAT22-61","TypeOffre":"007","NoArticleFacturation":"BA102305","DescriptionOffre":"Lot Flower","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":49.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":130.000,"DescrOffers":"1 Eau de Toilette + 1 Bain Mopussant + 1 Déo Vapo"},
  {"OffersNo":"OF23-00488","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000727","DescriptionOffre":"Lot Déo","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":11.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":20.000,"DescrOffers":"2 Déo à Bille au choix"},
  {"OffersNo":"OF23-00533","CatalogueNo":"CAT22-61","TypeOffre":"003","NoArticleFacturation":"P000741","DescriptionOffre":"Lot Face","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":54.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":162.000,"DescrOffers":"1 Fond de Teint au choix + 1 Pinceau "},
  {"OffersNo":"OF23-00489","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102304","DescriptionOffre":"Lot Individual Blue","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":54.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":98.000,"DescrOffers":"1 Eau de Toilette + 1 Déo à Bille"},
  {"OffersNo":"OF23-00534","CatalogueNo":"CAT22-61","TypeOffre":"001","NoArticleFacturation":"P000742","DescriptionOffre":"Lot Make up","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":35.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":114.000,"DescrOffers":"1 Mascara + 1 Ligneur + 1 Baume à Lèvres au choix "},
  {"OffersNo":"OF23-00490","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102305","DescriptionOffre":"Lot Full Speed Quantum","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":82.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":144.000,"DescrOffers":"1 Eau de Toilette + 1 Gel-Douche + 1 Déo à Bille"},
  {"OffersNo":"OF23-00535","CatalogueNo":"CAT22-61","TypeOffre":"003","NoArticleFacturation":"P000743","DescriptionOffre":"Lot Lash","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":29.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":82.000,"DescrOffers":"1 Mascara + 1 Ligneur au choix "},
  {"OffersNo":"OF23-00491","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102306","DescriptionOffre":"Lot Perceive","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":129.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":228.000,"DescrOffers":"1 Perceive Elle + 1 Perceive Lui"},
  
  
  
  
  
  
  {"OffersNo":"OF23-00537","CatalogueNo":"CAT22-61","TypeOffre":"003","NoArticleFacturation":"P000744","DescriptionOffre":"Lot Beauty","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":29.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":75.000,"DescrOffers":"1 Liquide Hydratant + 1 Fragrance en format de Sac"},
  {"OffersNo":"OF23-00493","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102307","DescriptionOffre":"Lot LBD","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":129.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":228.000,"DescrOffers":"2 Fragrances LBD"},
  {"OffersNo":"OF23-00538","CatalogueNo":"CAT22-61","TypeOffre":"003","NoArticleFacturation":"P000745","DescriptionOffre":"Lot Volume","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":32.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":82.000,"DescrOffers":"1 Mascara + 1 Crayon Khôl au choix"},
  {"OffersNo":"OF23-00494","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102308","DescriptionOffre":"Lot Full Speed","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":119.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":212.000,"DescrOffers":"1 Full Speed + 1 Full Speed Surfer"},
  {"OffersNo":"OF23-00539","CatalogueNo":"CAT22-61","TypeOffre":"003","NoArticleFacturation":"P000746","DescriptionOffre":"Lot Women","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":39.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":117.000,"DescrOffers":"1 Fragrances fen format de voyage + 1 RAL Liquide au choix"},
  {"OffersNo":"OF23-00495","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102322","DescriptionOffre":"Lot Attraction Lui","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":80.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":142.000,"DescrOffers":"1 Eau de Toilette + 1 Gel-Douche"},
  {"OffersNo":"OF23-00540","CatalogueNo":"CAT22-61","TypeOffre":"007","NoArticleFacturation":"BA102308","DescriptionOffre":"Lot Black","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":20.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":80.000,"DescrOffers":"1 Ligneur + 1 Crayon"},
  {"OffersNo":"OF23-00496","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102323","DescriptionOffre":"Lot True 1","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":41.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":76.000,"DescrOffers":"1 Stylo + 1 Huile Lèvres"},
  {"OffersNo":"OF23-00541","CatalogueNo":"CAT22-61","TypeOffre":"003","NoArticleFacturation":"P000747","DescriptionOffre":"Lot Girl","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":24.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":68.000,"DescrOffers":"1 Mascara + 1 Eyeliner Stick au choix"},
  {"OffersNo":"OF23-00497","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102324","DescriptionOffre":"Lot True 2","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":72.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":138.000,"DescrOffers":"1 Crayon Yeux + 1 Ombre à paupières + 1 Baume Lèvres"},
  {"OffersNo":"OF23-00542","CatalogueNo":"CAT22-61","TypeOffre":"007","NoArticleFacturation":"BA102309","DescriptionOffre":"Lot Pink ","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":16.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":56.000,"DescrOffers":"1 RAL mat + 1 Crème pour les Mains "},
  {"OffersNo":"OF23-00498","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102325","DescriptionOffre":"Lot Reversalist","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":124.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":220.000,"DescrOffers":"1 Crème de Jour + 1 Crème de Nuit "},
  {"OffersNo":"OF23-00543","CatalogueNo":"CAT22-61","TypeOffre":"007","NoArticleFacturation":"BA102310","DescriptionOffre":"Lot Jasmine","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":21.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":53.000,"DescrOffers":"1 Bain Moussant + 1 Brume "},
  {"OffersNo":"OF23-00499","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102326","DescriptionOffre":"Lot Ultimate","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":144.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":260.000,"DescrOffers":"1 Crème de Jour + 1 Crème de Nuit"},
  {"OffersNo":"OF23-00544","CatalogueNo":"CAT22-61","TypeOffre":"007","NoArticleFacturation":"BA102311","DescriptionOffre":"Lot Shower","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":21.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":53.000,"DescrOffers":"1 Bain Moussant + 1 Brume"},
  {"OffersNo":"OF23-00500","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102327","DescriptionOffre":"Lot Platinum","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":149.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":272.000,"DescrOffers":"1 Crème de Jour + 1 Crème de Nuit"},
  {"OffersNo":"OF23-00545","CatalogueNo":"CAT22-61","TypeOffre":"007","NoArticleFacturation":"BA102312","DescriptionOffre":"Lot Juice","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":18.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":56.000,"DescrOffers":"1 Bain Moussant + 1 Brume "},{"OffersNo":"OF23-00501","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000729","DescriptionOffre":"Lot Musk ","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":89.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":176.000,"DescrOffers":"2 Musk au choix"},
  {"OffersNo":"OF23-00546","CatalogueNo":"CAT22-61","TypeOffre":"004","NoArticleFacturation":"P000748","DescriptionOffre":"2 Gels-Douches au choix","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":17.500,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"02","PrixRegulier":44.000,"DescrOffers":"2 Gels-Douches au choix "},
  {"OffersNo":"OF23-00502","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102309","DescriptionOffre":"Lot Pur Blanca","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":45.900,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":88.000,"DescrOffers":"1 Eau de Toilette + 1 Déo à Bille"},{"OffersNo":"OF23-00503","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102310","DescriptionOffre":"Lot Wild Country","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":71.900,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":138.000,"DescrOffers":"1 Eau de Toilette + 1 Déo en Vapo + 1 Gel-Douche"},{"OffersNo":"OF23-00504","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102311","DescriptionOffre":"Lot TTA Today","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":94.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":175.000,"DescrOffers":"1 Eau de Parfum + 1 Lait Corps"},{"OffersNo":"OF23-00505","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102312","DescriptionOffre":"Lot TTA","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":94.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":168.000,"DescrOffers":"1 Eau de Toilette + 1 Gel-Douche"},
  {"OffersNo":"OF23-00506","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102313","DescriptionOffre":"Lot Deeply","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":44.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":91.000,"DescrOffers":"1 Shampooing + 1 Après-Shampooing + 1 Gommage"},
  {"OffersNo":"OF23-00507","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102314","DescriptionOffre":"Lot Keratine","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":27.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":47.000,"DescrOffers":"1 Shampooing + 1 Après-Shampooing"},
  {"OffersNo":"OF23-00508","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102315","DescriptionOffre":"Lot Curls","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":33.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":60.000,"DescrOffers":"1 Shampooing + 1 Après-Shampooing + 1 Crème"},
  {"OffersNo":"OF23-00509","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000730","DescriptionOffre":"Lot Advance Techniques 250ml","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":21.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":40.000,"DescrOffers":"2 Après-Shampooing 250ml au choix "},{"OffersNo":"OF23-00510","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000731","DescriptionOffre":"Lot Bain Moussant 500ml","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":28.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":48.000,"DescrOffers":"2 Bain Moussants 500ml au choix "},{"OffersNo":"OF23-00511","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000732","DescriptionOffre":"Lot Brume 2 ","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":23.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":42.000,"DescrOffers":"2 Brumes au choix "},
  {"OffersNo":"OF23-00512","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102316","DescriptionOffre":"Lot Lavander","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":30.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":56.000,"DescrOffers":"1 Crème Pieds + 1 Vaporisateur"},{"OffersNo":"OF23-00513","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000733","DescriptionOffre":"Lot Footworks","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":26.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":48.000,"DescrOffers":"2 Crèmes Footworks au choix"},
  {"OffersNo":"OF23-00514","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102317","DescriptionOffre":"Lot Girls","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":38.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":70.000,"DescrOffers":"1 Lait Corps + 1 Brume + 1 Gel Douche"},
  {"OffersNo":"OF23-00515","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102318","DescriptionOffre":"Lot Spiderman","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":51.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":96.000,"DescrOffers":"1 Eau de Cologne + 1 Shampooing + 1 Gel Cheveux"},
  {"OffersNo":"OF23-00516","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102319","DescriptionOffre":"Lot Frozen","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":52.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":94.000,"DescrOffers":"1 Eau de Cologne + 1 Vaporisateur"},
  {"OffersNo":"OF23-00517","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000734","DescriptionOffre":"Lot Kids","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":27.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":48.000,"DescrOffers":"2 Produits Kids au choix "},
  {"OffersNo":"OF23-00518","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102320","DescriptionOffre":"Lot Works","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":44.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":97.000,"DescrOffers":"1 Crème Dépilatoire Corps + 1 Crème Dépilatoire Visage"},
  {"OffersNo":"OF23-00519","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000735","DescriptionOffre":"Lot Avon Care 400ml","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":38.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":80.000,"DescrOffers":"2 Laits Corps 400ml au choix"},
  {"OffersNo":"OF23-00520","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000736","DescriptionOffre":"Lot Avon Care ","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":40.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":72.000,"DescrOffers":"2 Crème Multi-Usages au choix "},{"OffersNo":"OF23-00521","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000737","DescriptionOffre":"Lot Avon Care 75ml","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":14.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":28.000,"DescrOffers":"2 Crème pour les Mains au choix"},
  {"OffersNo":"OF23-00522","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000738","DescriptionOffre":"Lot Avon Care 2 ","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":38.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":60.000,"DescrOffers":"2 Laits Corps 400ml au choix "},{"OffersNo":"OF23-00523","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000739","DescriptionOffre":"Lot Avon Care 700ml","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":33.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":64.000,"DescrOffers":"2 Shampooing 700ml au choix"},{"OffersNo":"OF23-00524","CatalogueNo":"CAT22-60","TypeOffre":"004","NoArticleFacturation":"P000740","DescriptionOffre":"Lot Advance Techniques 700ml","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":36.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":64.000,"DescrOffers":"2 Shampooing Advance Techniques 700ml au choix"},{"OffersNo":"OF23-00525","CatalogueNo":"CAT22-60","TypeOffre":"007","NoArticleFacturation":"BR102321","DescriptionOffre":"Super Lot","TypeResultatOffre":0,"FormeResultatOffre":0,"PrixResultatOffre":89.000,"PourcentageRemiseOffre":"0","QteResultatOffre":0,"Ncompagne":"","DescriptionType":"","TypeOffreBRBA":"01","PrixRegulier":180.000,"DescrOffers":"Super Lot"}
  
  
  
    
    ];
    export default productsData